### ISSUE TITLE
Link to ideas.obsproject.com to reduce comment spam.

### ISSUE THREAD

**Issue by indolering** [obsproject/rfcs#36]
There is a lot of comment spam on RFC pull requests ("+1", "please implement this", etc).  I think including something like the following at the top of the PR template would help reduce this:

>⚠️ Show your support for this feature by voting on [ideas.obsproject.com](https://ideas.obsproject.com/posts/####/idea-title) or through [Github reactions](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/). Do not post non-technical comments (i.e "+1") here!

**Comment by kkartaltepe** [comment]
+1 :)

**Comment by Fenrirthviti** [comment]
This hasn't really been an issue here, so going to close.
