### ISSUE TITLE
[Linux/Wayland] Stream preview not displayed

### ISSUE THREAD

**Issue by thelazy6** [obsproject/rfcs#38]
## Platform
Operating system and version: Fedora 34 (GNOME 40 Wayland/Linux 5.11)
OBS Studio version: 26.1.2
OBS Log file: [2021-03-22 10-02-13.txt](https://github.com/obsproject/rfcs/files/6180867/2021-03-22.10-02-13.txt)

## Expected Behavior
The same as on X11/Xwayland also in wayland.
Wayland (note the white area is actually transparent/shows my desktop background): ![Bildschirmfoto von 2021-03-22 10-19-07](https://user-images.githubusercontent.com/62787185/111967304-2b6cb880-8af8-11eb-828d-64da809ef2b1.png)
X11/Xwayland (expected, the red slide covers my webcam): ![Bildschirmfoto von 2021-03-22 10-21-23](https://user-images.githubusercontent.com/62787185/111967492-67a01900-8af8-11eb-8ae5-e37fead61db9.png)

## Current Behavior
See wayland screenshot above.

## Steps to Reproduce

1. Wayland: Run with environment variable `QT_QPA_PLATFORM=wayland`
2. Xwayland: Run with environment variable `QT_QPA_PLATFORM=xcb`

**Comment by WizardCM** [comment]
Correct, 26.1.2 doesn't support Wayland, but 27 will. We'll be nearing a beta soon. Additionally, the RFC repo isn't for OBS Studio bug reports.
